name: Selenium Tests

on:
  workflow_run:
    workflows: ["PetStore API Tests"]  # nome exato do seu api-tests.yml
    types:
      - completed

jobs:
  selenium-tests:
    name: Selenium Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Selenium Tests
        env:
          USUARIO: standard_user
          SENHA: secret_sauce
          NOME: Cristiano
          SOBRENOME: Ronaldo
          CODIGO_POSTAL: 01001000
        run: python test_compra.py

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-report
          path: reports/
